app:
  system_name: "xxxx"
  name: "admin-main" #应用名称
  port: 8089    #应用启动端口
  version: "2.0" #应用版本
  grace_reload: 1  #是否支持优雅重启
  app_api_version: "v1"
  app_need_p_prof: false
  administrator: "zhaocj2009@126.com"
  app_run_timer_task: false